---
title: "Projects"
---

```{r include=FALSE}
library(glue)
library(jsonlite)
library(dplyr)
library(bslib)
library(bsicons)
library(htmltools)
library(stringr)
```

```{r fxns, include=FALSE}
make_lis <- function(tbl) {
  for (i in apply(tbl, 1, as.list)) {
    cat("{{< fa box-open >}}  ")
    cat(glue("<a href={i$html_url} target='_blank'>{ i$name}</a> {ifelse(is.null(i$description), '', paste0('- ' , glue::trim(i$description)))}"), sep = "\n")
    cat("\n")
  }
}
filter_topic <- function(.data, topic) {
  filter(.data, grepl(topic, topics))
}

as_badge <- function(x) {
  a(img(src = x$src, alt = x$alt), href = x$href, target = "_blank")
}

make_badge <- function(df) {
  badge <- df$badges[which(grepl("getwilds.github.io|getwilds.org", df$badges$src)), ]
  as_badge(badge)
  # a(img(src = badge$src, alt = badge$alt), href = badge$href, target = "_blank")
}

make_card <- function(row) {
  card(
    class = "rounded-3",
    card_header(
      bsicons::bs_icon("box"),
      strong(row$name)
    ),
    card_body(
      fillable = FALSE,
      row$description
    ),
    card_body(
      fillable = FALSE,
      class = "bg-light d-inline-flex justify-content-between align-items-center",
      a(bsicons::bs_icon("github"), href = row$html_url, target = "_blank"),
      make_badge(row)
    )
  )
}

make_cards <- function(tbl) {
  layout_column_wrap(!!!apply(tbl, 1, make_card), width = 1 / 2)
}
```

```{r pkgs-by-topic, include=FALSE}
registry_url <- "https://getwilds.org/registry/registry.json"
repos <- as_tibble(fromJSON(registry_url)$repos) %>%
  filter(!private) %>%
  filter(!fork)

wilds_r <- repos %>% filter_topic("wilds-r")
wilds_py <- repos %>% filter_topic("wilds-py")
wilds_docker <- repos %>% filter_topic("wilds-docker")
wilds_comp <- repos %>% filter_topic("wilds-comp")
wilds_wdl <- repos %>% filter_topic("wilds-wdl")
wilds_nf <- repos %>% filter_topic("wilds-nf")
```

### R Packages

```{r r-pkgs, echo=FALSE, results="asis"}
if (NROW(wilds_r) == 0) cat("Coming soon!") else make_cards(wilds_r)
```

### Python Packages

```{r python-pkgs, echo=FALSE, results="asis"}
if (NROW(wilds_py) == 0) cat("Coming soon!") else make_cards(wilds_py)
```

### Docker Recipes

```{r docker, echo=FALSE, results="asis"}
if (NROW(wilds_docker) == 0) cat("Coming soon!") else make_cards(wilds_docker)
```

### Research Compendia

```{r rc, echo=FALSE, results="asis"}
if (NROW(wilds_comp) == 0) cat("Coming soon!") else make_cards(wilds_comp)
```

### WDLs

```{r wdl, echo=FALSE, results="asis"}
if (NROW(wilds_wdl) == 0) cat("Coming soon!") else make_cards(wilds_wdl)
```

### NextFlow

```{r nf, echo=FALSE, results="asis"}
if (NROW(wilds_nf) == 0) cat("Coming soon!") else make_cards(wilds_nf)
```

### Repos status tally

```{r repo-status, echo=FALSE, results="asis"}
make_badge_body <- function(x) {
  card_body(
    fillable = FALSE,
    class = "bg-light d-inline-flex",
    as_badge(x),
    span(HTML("&nbsp;"), bsicons::bs_icon("arrow-right-square"), HTML("&nbsp;"), x$n)
  )
}
target_topics <- c("wilds-r","wilds-py","wilds-docker","wilds-comp","wilds-wdl","wilds-nf")
the_repos <- repos %>% filter_topic(paste(target_topics, collapse = "|"))
repos_calc <- bind_rows(lapply(the_repos$badges, function(df) {
  df[which(grepl("getwilds.github.io|getwilds.org", df$src)), ]
})) %>%
  mutate(
    status = str_extract(href, "(?<=#).*"),
    href = str_replace_all(href, "getwilds.github.io", "getwilds.org"),
    src = str_replace_all(src, "getwilds.github.io", "getwilds.org")
  ) %>%
  group_by(status) %>%
  mutate(n = n()) %>%
  distinct() %>%
  ungroup()
card(
  #!!!apply(repos_calc, 1, function(w) make_badge_body(as.data.frame(w))),
  class = "rounded-3",
  make_badge_body(repos_calc[1,]),
  make_badge_body(repos_calc[2,]),
  make_badge_body(repos_calc[3,])
)
```
